name: Fly Deploy
on:
  push:
    branches:
      - main
      - feature/deploy
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  MONGO_URI: ${{ secrets.MONGO_URI }}

jobs:
  deploy_be:
    name: Deploy app backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: cd server && flyctl deploy --remote-only
  deploy_fe:
    name: Deploy app frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: cd client && flyctl deploy --remote-only
